name: test-variables

on:
  workflow_dispatch:

env:
  MY_ENV_VAR: "Hello from caller!"

jobs:
  job1:
    name: A job to test variables
    runs-on: ubuntu-latest
    steps:
      - name: 'echo workflow level environment variable'
        run: |
          echo "MY_ENV_VAR: ${{ env.MY_ENV_VAR }}"

      - name: 'Get repository variable DEFAULT_NODE_VERSION'
        run: |
          echo "DEFAULT_NODE_VERSION: ${{ vars.DEFAULT_NODE_VERSION }}"
  
  job-Development:
    environment: Development
    needs: [job1]
    name: A job to test Development environment variables
    runs-on: ubuntu-lastest
    steps:
      - name: 'Get variable from Development environment'
        run: |
          echo "DEFAULT_NODE_VERSION: ${{ vars.DEFAULT_NODE_VERSION }}"

  job-Staging:
    environment: Staging
    needs: [job-Development]
    name: A job to test Staging environment variables
    runs-on: ubuntu-lastest
    steps:
      - name: 'Get variable from Staging environment'
        run: |
          echo "DEFAULT_NODE_VERSION: ${{ vars.DEFAULT_NODE_VERSION }}"




